name: news_app
description: A news app built with flutter and news api endpoint.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_app_name: ^0.1.1
  flutter_launcher_icons: ^0.11.0
  cupertino_icons: ^1.0.2
  dio: ^5.2.1+1
  carousel_slider: ^4.2.1
  intl: ^0.18.1
  url_launcher: ^6.1.11

# App Name
flutter_app_name:
  name: 'News App'

# App Icon
flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/favicon.png'
  min_sdk_android: 21

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/favicon.png